# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_ui_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugWindow(object):
    def setupUi(self, DebugWindow):
        DebugWindow.setObjectName("DebugWindow")
        DebugWindow.resize(443, 550)
        self.centralWidget = QtWidgets.QWidget(DebugWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.btnManualStop = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualStop.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualStop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualStop.setObjectName("btnManualStop")
        self.gridLayout.addWidget(self.btnManualStop, 9, 2, 1, 1)
        self.btnSetFilter = QtWidgets.QPushButton(self.centralWidget)
        self.btnSetFilter.setMinimumSize(QtCore.QSize(50, 0))
        self.btnSetFilter.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSetFilter.setObjectName("btnSetFilter")
        self.gridLayout.addWidget(self.btnSetFilter, 4, 2, 1, 1)
        self.btnManualGetWaveLength = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualGetWaveLength.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualGetWaveLength.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualGetWaveLength.setObjectName("btnManualGetWaveLength")
        self.gridLayout.addWidget(self.btnManualGetWaveLength, 10, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 11, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btnCalib = QtWidgets.QPushButton(self.centralWidget)
        self.btnCalib.setMinimumSize(QtCore.QSize(50, 0))
        self.btnCalib.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnCalib.setObjectName("btnCalib")
        self.gridLayout.addWidget(self.btnCalib, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.lineSetWL = QtWidgets.QLineEdit(self.centralWidget)
        self.lineSetWL.setMinimumSize(QtCore.QSize(50, 0))
        self.lineSetWL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineSetWL.setObjectName("lineSetWL")
        self.gridLayout.addWidget(self.lineSetWL, 0, 1, 1, 1)
        self.btnManualForward = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualForward.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualForward.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualForward.setObjectName("btnManualForward")
        self.gridLayout.addWidget(self.btnManualForward, 7, 2, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.centralWidget)
        self.btnStop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 14, 2, 1, 1)
        self.btnSetWL = QtWidgets.QPushButton(self.centralWidget)
        self.btnSetWL.setMinimumSize(QtCore.QSize(50, 0))
        self.btnSetWL.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSetWL.setObjectName("btnSetWL")
        self.gridLayout.addWidget(self.btnSetWL, 0, 2, 1, 1)
        self.lineFilter = QtWidgets.QLineEdit(self.centralWidget)
        self.lineFilter.setMinimumSize(QtCore.QSize(50, 0))
        self.lineFilter.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineFilter.setObjectName("lineFilter")
        self.gridLayout.addWidget(self.lineFilter, 4, 1, 1, 1)
        self.btnManualFaster = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualFaster.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualFaster.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualFaster.setObjectName("btnManualFaster")
        self.gridLayout.addWidget(self.btnManualFaster, 11, 2, 1, 1)
        self.btnSetWLWO = QtWidgets.QPushButton(self.centralWidget)
        self.btnSetWLWO.setMinimumSize(QtCore.QSize(50, 0))
        self.btnSetWLWO.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSetWLWO.setObjectName("btnSetWLWO")
        self.gridLayout.addWidget(self.btnSetWLWO, 1, 2, 1, 1)
        self.btnMeasure = QtWidgets.QPushButton(self.centralWidget)
        self.btnMeasure.setMinimumSize(QtCore.QSize(50, 0))
        self.btnMeasure.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnMeasure.setObjectName("btnMeasure")
        self.gridLayout.addWidget(self.btnMeasure, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 12, 0, 1, 1)
        self.btnManualBeginMode = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualBeginMode.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualBeginMode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualBeginMode.setObjectName("btnManualBeginMode")
        self.gridLayout.addWidget(self.btnManualBeginMode, 5, 2, 1, 1)
        self.labelResult = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.gridLayout.addWidget(self.labelResult, 14, 0, 1, 1)
        self.btnManualReverse = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualReverse.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualReverse.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualReverse.setObjectName("btnManualReverse")
        self.gridLayout.addWidget(self.btnManualReverse, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.btnManualSlower = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualSlower.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualSlower.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualSlower.setObjectName("btnManualSlower")
        self.gridLayout.addWidget(self.btnManualSlower, 12, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.lineSetWLWO = QtWidgets.QLineEdit(self.centralWidget)
        self.lineSetWLWO.setMinimumSize(QtCore.QSize(50, 0))
        self.lineSetWLWO.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineSetWLWO.setObjectName("lineSetWLWO")
        self.gridLayout.addWidget(self.lineSetWLWO, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 10, 0, 1, 1)
        self.btnManualEndMode = QtWidgets.QPushButton(self.centralWidget)
        self.btnManualEndMode.setMinimumSize(QtCore.QSize(50, 0))
        self.btnManualEndMode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnManualEndMode.setObjectName("btnManualEndMode")
        self.gridLayout.addWidget(self.btnManualEndMode, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 0, 1, 1)
        DebugWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DebugWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 443, 21))
        self.menuBar.setObjectName("menuBar")
        DebugWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DebugWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        DebugWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DebugWindow)
        self.statusBar.setObjectName("statusBar")
        DebugWindow.setStatusBar(self.statusBar)

        self.retranslateUi(DebugWindow)
        QtCore.QMetaObject.connectSlotsByName(DebugWindow)

    def retranslateUi(self, DebugWindow):
        _translate = QtCore.QCoreApplication.translate
        DebugWindow.setWindowTitle(_translate("DebugWindow", "MainWindow"))
        self.label_8.setText(_translate("DebugWindow", "Начать режим ручного управления"))
        self.btnManualStop.setText(_translate("DebugWindow", "OK"))
        self.btnSetFilter.setText(_translate("DebugWindow", "OK"))
        self.btnManualGetWaveLength.setText(_translate("DebugWindow", "OK"))
        self.label_14.setText(_translate("DebugWindow", "Р.Р.У: Скорость - быстрее"))
        self.label_12.setText(_translate("DebugWindow", "Р.Р.У: Остановить"))
        self.label_3.setText(_translate("DebugWindow", "Измерить"))
        self.btnCalib.setText(_translate("DebugWindow", "OK"))
        self.label_9.setText(_translate("DebugWindow", "Остановить р.р.у"))
        self.lineSetWL.setText(_translate("DebugWindow", "600"))
        self.btnManualForward.setText(_translate("DebugWindow", "OK"))
        self.btnStop.setText(_translate("DebugWindow", "STOP"))
        self.btnSetWL.setText(_translate("DebugWindow", "OK"))
        self.lineFilter.setText(_translate("DebugWindow", "1"))
        self.btnManualFaster.setText(_translate("DebugWindow", "OK"))
        self.btnSetWLWO.setText(_translate("DebugWindow", "OK"))
        self.btnMeasure.setText(_translate("DebugWindow", "OK"))
        self.label_2.setText(_translate("DebugWindow", "Установить длину волны без учета д.р."))
        self.label_15.setText(_translate("DebugWindow", "Р.Р.У: Скорость - медленнее"))
        self.btnManualBeginMode.setText(_translate("DebugWindow", "OK"))
        self.labelResult.setText(_translate("DebugWindow", "0"))
        self.btnManualReverse.setText(_translate("DebugWindow", "OK"))
        self.label_7.setText(_translate("DebugWindow", "Установить фильтр"))
        self.btnManualSlower.setText(_translate("DebugWindow", "OK"))
        self.label_4.setText(_translate("DebugWindow", "Калибровать"))
        self.label_10.setText(_translate("DebugWindow", "Р.Р.У: Вперед"))
        self.lineSetWLWO.setText(_translate("DebugWindow", "300"))
        self.label_13.setText(_translate("DebugWindow", "Р.Р.У: Получить длину волны"))
        self.btnManualEndMode.setText(_translate("DebugWindow", "OK"))
        self.label.setText(_translate("DebugWindow", "Установить длину волны"))
        self.label_11.setText(_translate("DebugWindow", "Р.Р.У: Назад"))


