# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proc_ui_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 783)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setSpacing(6)
        self.chartLayout.setObjectName("chartLayout")
        self.gridLayout_2.addLayout(self.chartLayout, 1, 0, 1, 1)
        self.verticalWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineXMax = QtWidgets.QLineEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineXMax.setFont(font)
        self.lineXMax.setObjectName("lineXMax")
        self.gridLayout.addWidget(self.lineXMax, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineYMax = QtWidgets.QLineEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineYMax.setFont(font)
        self.lineYMax.setObjectName("lineYMax")
        self.gridLayout.addWidget(self.lineYMax, 4, 2, 1, 1)
        self.lineXMin = QtWidgets.QLineEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineXMin.setFont(font)
        self.lineXMin.setObjectName("lineXMin")
        self.gridLayout.addWidget(self.lineXMin, 3, 1, 1, 1)
        self.btnTest = QtWidgets.QPushButton(self.verticalWidget)
        self.btnTest.setMinimumSize(QtCore.QSize(150, 0))
        self.btnTest.setObjectName("btnTest")
        self.gridLayout.addWidget(self.btnTest, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.verticalWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineYMin = QtWidgets.QLineEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineYMin.setFont(font)
        self.lineYMin.setObjectName("lineYMin")
        self.gridLayout.addWidget(self.lineYMin, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.verticalWidget, 1, 1, 1, 1)
        self.chartViewControl = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartViewControl.sizePolicy().hasHeightForWidth())
        self.chartViewControl.setSizePolicy(sizePolicy)
        self.chartViewControl.setMinimumSize(QtCore.QSize(0, 40))
        self.chartViewControl.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chartViewControl.setObjectName("chartViewControl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chartViewControl)
        self.horizontalLayout.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkChart1 = QtWidgets.QCheckBox(self.chartViewControl)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chkChart1.setFont(font)
        self.chkChart1.setObjectName("chkChart1")
        self.horizontalLayout.addWidget(self.chkChart1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.chartViewControl, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1159, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.qActionOpenFile = QtWidgets.QAction(MainWindow)
        self.qActionOpenFile.setObjectName("qActionOpenFile")
        self.menuExit = QtWidgets.QAction(MainWindow)
        self.menuExit.setObjectName("menuExit")
        self.qActionShow = QtWidgets.QAction(MainWindow)
        self.qActionShow.setObjectName("qActionShow")
        self.qActionMDRConnect = QtWidgets.QAction(MainWindow)
        self.qActionMDRConnect.setObjectName("qActionMDRConnect")
        self.qActionCalibrate = QtWidgets.QAction(MainWindow)
        self.qActionCalibrate.setObjectName("qActionCalibrate")
        self.qActionOpen = QtWidgets.QAction(MainWindow)
        self.qActionOpen.setObjectName("qActionOpen")
        self.qActionExit = QtWidgets.QAction(MainWindow)
        self.qActionExit.setObjectName("qActionExit")
        self.menu.addAction(self.qActionOpen)
        self.menu.addSeparator()
        self.menu.addAction(self.qActionExit)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineXMax.setText(_translate("MainWindow", "600"))
        self.label.setText(_translate("MainWindow", "X"))
        self.lineYMax.setText(_translate("MainWindow", "100"))
        self.lineXMin.setText(_translate("MainWindow", "0"))
        self.btnTest.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.lineYMin.setText(_translate("MainWindow", "0"))
        self.chkChart1.setText(_translate("MainWindow", "1"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.qActionOpenFile.setText(_translate("MainWindow", "Открыть"))
        self.menuExit.setText(_translate("MainWindow", "Выход"))
        self.qActionShow.setText(_translate("MainWindow", "Show"))
        self.qActionMDRConnect.setText(_translate("MainWindow", "MDR"))
        self.qActionCalibrate.setText(_translate("MainWindow", "Calibrate"))
        self.qActionOpen.setText(_translate("MainWindow", "Открыть"))
        self.qActionExit.setText(_translate("MainWindow", "Выход"))


